# Generated by Django 5.2 on 2025-12-07 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AI for Culture', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '课题组信息',
                'verbose_name_plural': '课题组信息',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('professor', '教授'), ('associate_professor', '副教授'), ('lecturer', '讲师'), ('postdoctoral', '博士后'), ('phd', '博士研究生'), ('master', '硕士研究生'), ('undergraduate', '本科生'), ('research_assistant', '研究助手'), ('other', '其他')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_leader', models.BooleanField(default=False, help_text='是否为课题组负责人')),
                ('order', models.IntegerField(default=0, help_text='排序权重')),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '联系消息',
                'verbose_name_plural': '联系消息',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='简短描述', null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '最新动态',
                'verbose_name_plural': '最新动态',
                'ordering': ['-publish_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='排序权重')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(help_text='作者列表，逗号分隔', max_length=500)),
                ('type', models.CharField(choices=[('conference', '会议论文'), ('journal', '期刊论文'), ('book', '专著'), ('book_chapter', '章节'), ('other', '其他')], max_length=20)),
                ('venue', models.CharField(blank=True, help_text='会议或期刊名称', max_length=200, null=True)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField(blank=True, null=True)),
                ('paper_url', models.URLField(blank=True, null=True)),
                ('citation_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': '学术成果',
                'verbose_name_plural': '学术成果',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='排序权重')),
            ],
            options={
                'verbose_name': '研究方向',
                'verbose_name_plural': '研究方向',
                'ordering': ['order', 'id'],
            },
        ),
    ]
