# Generated by Django 5.2 on 2025-12-10 02:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='researcharea',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='成立日期'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='使命'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='name',
            field=models.CharField(default='AI for Culture', max_length=100, verbose_name='课题组名称'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='愿景'),
        ),
        migrations.AlterField(
            model_name='groupinfo',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='网站地址'),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='照片链接'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='是否为课题组负责人', verbose_name='是否为负责人'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='order',
            field=models.IntegerField(default=0, help_text='排序权重', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('professor', '教授'), ('associate_professor', '副教授'), ('lecturer', '讲师'), ('postdoctoral', '博士后'), ('phd', '博士研究生'), ('master', '硕士研究生'), ('undergraduate', '本科生'), ('research_assistant', '研究助手'), ('other', '其他')], max_length=20, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='头衔'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回复时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_content',
            field=models.TextField(blank=True, null=True, verbose_name='回复内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, help_text='简短描述', null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.URLField(blank=True, null=True, verbose_name='logo链接'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.IntegerField(default=0, help_text='排序权重', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='网站链接'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(help_text='作者列表，逗号分隔', max_length=500, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='引用次数'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paper_url',
            field=models.URLField(blank=True, null=True, verbose_name='论文链接'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=500, verbose_name='论文标题'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('conference', '会议论文'), ('journal', '期刊论文'), ('book', '专著'), ('book_chapter', '章节'), ('other', '其他')], max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='venue',
            field=models.CharField(blank=True, help_text='会议或期刊名称', max_length=200, null=True, verbose_name='发表刊物'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(verbose_name='发表年份'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='description',
            field=models.TextField(verbose_name='简短描述'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='详细介绍'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='研究方向名称'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='order',
            field=models.IntegerField(default=0, help_text='排序权重', verbose_name='排序'),
        ),
    ]
