# Generated by Django 5.2 on 2025-12-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_news_image_url_remove_researcharea_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='office',
            field=models.CharField(default='无办公室', max_length=50, verbose_name='办公室'),
        ),
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年级'),
        ),
    ]
