# Generated by Django 5.2 on 2026-01-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_member_office_member_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupInfo',
        ),
        migrations.AlterModelOptions(
            name='researcharea',
            options={'ordering': ['order', 'id'], 'verbose_name': '研究领域', 'verbose_name_plural': '研究领域'},
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('professor', '教授'), ('associate_professor', '副教授'), ('lecturer', '讲师'), ('postdoctoral', '博士后'), ('phd', '博士研究生'), ('master', '硕士研究生'), ('undergraduate', '本科生'), ('research_assistant', '研究助手'), ('graduate', '毕业生'), ('other', '其他')], max_length=20, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='研究领域'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('conference', '会议论文'), ('journal', '期刊论文'), ('other', '其他')], max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='name',
            field=models.CharField(max_length=100, verbose_name='研究领域名称'),
        ),
    ]
