# Generated by Django 5.2 on 2026-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_groupinfo_alter_researcharea_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bio',
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, help_text='请填写手机号或固定电话', max_length=20, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('head', '系主任'), ('professor', '教授'), ('associate_professor', '副教授'), ('lecturer', '讲师'), ('postdoctoral', '博士后'), ('phd', '博士研究生'), ('master', '硕士研究生'), ('undergraduate', '本科生'), ('research_assistant', '研究助手'), ('graduate', '毕业生'), ('other', '其他')], max_length=20, verbose_name='职位'),
        ),
    ]
