# Generated by Django 5.2 on 2026-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_member_bio_member_phone_alter_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image_url',
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='用户头像'),
        ),
    ]
