# Generated by Django 5.2 on 2026-01-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_member_image_url_member_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bibtex_text',
            field=models.TextField(blank=True, help_text='粘贴BibTeX条目', null=True, verbose_name='BibTeX文本'),
        ),
    ]
