# Generated by Django 5.2 on 2026-01-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_publication_bibtex_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-month', 'title'], 'verbose_name': '学术成果', 'verbose_name_plural': '学术成果'},
        ),
        migrations.AddField(
            model_name='publication',
            name='month',
            field=models.IntegerField(default=1, verbose_name='发表月份'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='office',
            field=models.CharField(default='暂无办公室', max_length=50, verbose_name='办公室'),
        ),
    ]
