# Generated by Django 5.2 on 2026-01-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_publication_options_publication_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'title'], 'verbose_name': '学术成果', 'verbose_name_plural': '学术成果'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='month',
        ),
    ]
