# Generated by Django 5.2 on 2026-01-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_publication_options_remove_publication_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=500, unique=True, verbose_name='论文标题'),
        ),
    ]
