# Generated by Django 5.2 on 2026-01-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_member_year_alter_publication_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='year',
        ),
    ]
