# Generated by Django 5.2 on 2026-01-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_member_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='graduate_time',
            field=models.DateField(blank=True, null=True, verbose_name='毕业时间'),
        ),
        migrations.AddField(
            model_name='member',
            name='graduation_destination',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='毕业去向'),
        ),
    ]
