# Generated by Django 5.2 on 2026-01-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_member_graduate_time_member_graduation_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'order', 'title'], 'verbose_name': '学术成果', 'verbose_name_plural': '学术成果'},
        ),
        migrations.AddField(
            model_name='publication',
            name='order',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='排序权重'),
        ),
    ]
