# Generated by Django 5.2 on 2026-01-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_publication_options_publication_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='个人主页地址'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='order',
            field=models.IntegerField(blank=True, default=100, help_text='权重越小越靠前', null=True, verbose_name='排序权重'),
        ),
    ]
