# Generated by Django 5.2 on 2026-03-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_member_graduate_time_member_research_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='logo',
        ),
    ]
