# Generated by Django 5.2 on 2026-03-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_partner_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_content',
        ),
    ]
