# Generated by Django 5.2 on 2026-03-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_message_replied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
