# Generated by Django 5.2 on 2026-03-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_message_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('head', '系主任'), ('professor', '教授'), ('associate_professor', '副教授'), ('lecturer', '讲师'), ('postdoctoral', '博士后'), ('phd', '博士研究生'), ('master', '硕士研究生'), ('undergraduate', '本科生'), ('research_assistant', '研究助理'), ('graduate', '毕业生'), ('other', '其他')], max_length=20, verbose_name='职位'),
        ),
    ]
