# Generated by Django 5.2 on 2026-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_message_alter_member_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(help_text='作者列表，逗号分隔', max_length=255, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='论文标题'),
        ),
    ]
